// Auto-generated by generate-api-types.ts — do not edit manually

import type { paths as AuthPaths, components as AuthComponents } from './auth/auth'
import type { paths as UsersPaths, components as UsersComponents } from './users/users'

export type paths = AuthPaths & UsersPaths
export type components = AuthComponents & UsersComponents
