/**
 * 按后端模块拆分生成前端 API 类型文件。
 *
 * 流程：从 Hono 实例导出完整 OpenAPI spec → 按 /api/v1/{module}/ 前缀拆分 paths →
 * 每个模块生成独立的 .d.ts → 最后生成 index.d.ts 将所有模块类型合并导出。
 *
 * 产物结构（写入 apps/client/src/api/）：
 *   {module}/{module}.d.ts  — 每个模块一份，只含该模块的 paths，components 完整保留以避免引用缺失
 *   api-types.d.ts          — 合并所有模块的 paths 和 components 类型，供 openapi-fetch client 使用
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { app } from '../app.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

// 从 Hono 实例导出完整的 OpenAPI 3.1 spec（内存中的 JSON 对象，不落盘）
const fullSpec = app.getOpenAPI31Document({
  openapi: '3.1.0',
  info: { title: 'Server Template API', version: '1.0.0' },
  security: [{ BearerAuth: [] }],
})

// ==================== 按 URL 前缀分组 paths ====================
// 正则提取 /api/v1/{segment}/ 中的 segment（如 auth、users）
const MODULE_REGEX = /^\/api\/v1\/([^/]+)/
const moduleMap = new Map<string, string[]>()

const specPaths = fullSpec.paths ?? {}
for (const path of Object.keys(specPaths)) {
  const match = path.match(MODULE_REGEX)
  if (!match) continue
  const segment = match[1]
  let paths = moduleMap.get(segment)
  if (!paths) {
    paths = []
    moduleMap.set(segment, paths)
  }
  paths.push(path)
}

if (moduleMap.size === 0) {
  console.log('No API paths found, skipping type generation.')
  process.exit(0)
}

const apiDir = resolve(__dirname, '../../../client/src/api')

// ==================== 检测 components.schemas 重名 ====================
// 不同模块注册同名 schema 会导致 index.d.ts 交叉类型合并时产生意外行为
const allSchemaNames = Object.keys(fullSpec.components?.schemas ?? {})
const seenNames = new Set<string>()
for (const name of allSchemaNames) {
  if (seenNames.has(name)) {
    console.error(`Duplicate schema name detected: ${name}. Rename to avoid type conflicts.`)
    process.exit(1)
  }
  seenNames.add(name)
}

// ==================== 逐模块生成 .d.ts ====================
const moduleSegments: string[] = []

for (const [segment, paths] of moduleMap) {
  moduleSegments.push(segment)

  // 构造子 spec：过滤出该模块的 paths，保留完整 components（不做 schema 裁剪，避免引用缺失）
  const subPaths: Record<string, unknown> = {}
  for (const p of paths) {
    subPaths[p] = specPaths[p]
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Hono 返回的 spec 类型与 openapi-typescript 声明的 OpenAPI3 存在细微差异（如 info.license）
  const subSpec = {
    ...fullSpec,
    paths: subPaths,
    components: fullSpec.components,
  } as any

  // 使用 openapi-typescript Node API 直接从内存中的 spec 生成类型（无需中间 JSON 文件）
  const ast = await openapiTS(subSpec)
  const contents = astToString(ast)

  // 输出到 apps/client/src/api/{segment}/{segment}.d.ts（与模块的请求函数同目录）
  const moduleDir = resolve(apiDir, segment)
  mkdirSync(moduleDir, { recursive: true })
  const outputPath = resolve(moduleDir, `${segment}.d.ts`)
  writeFileSync(outputPath, contents, 'utf-8')
  console.log(`Generated: ${segment}/${segment}.d.ts (${paths.length} path${paths.length > 1 ? 's' : ''})`)
}

// ==================== 生成 api-types.d.ts 合并导出 ====================
// 用交叉类型（&）将所有模块的 paths 和 components 合并成一个完整类型，
// 这样 openapi-fetch 的 createClient<paths>() 只需从 api-types 导入即可使用所有接口
const indexLines: string[] = ['// Auto-generated by generate-api-types.ts — do not edit manually', '']

const imports: string[] = []
const pathMerges: string[] = []
const componentMerges: string[] = []

for (const segment of moduleSegments) {
  const pascalName = segment.charAt(0).toUpperCase() + segment.slice(1)
  imports.push(`import type { paths as ${pascalName}Paths, components as ${pascalName}Components } from './${segment}/${segment}'`)
  pathMerges.push(`${pascalName}Paths`)
  componentMerges.push(`${pascalName}Components`)
}

indexLines.push(...imports)
indexLines.push('')
indexLines.push(`export type paths = ${pathMerges.join(' & ')}`)
indexLines.push(`export type components = ${componentMerges.join(' & ')}`)
indexLines.push('')

const indexPath = resolve(apiDir, 'api-types.d.ts')
writeFileSync(indexPath, indexLines.join('\n'), 'utf-8')
console.log(`Generated: api-types.d.ts (merging ${moduleSegments.length} module${moduleSegments.length > 1 ? 's' : ''})`)
